(cl:defpackage mover-srv
  (:use )
  (:export
   "MOVEMENTCOMPLETE"
   "<MOVEMENTCOMPLETE-REQUEST>"
   "MOVEMENTCOMPLETE-REQUEST"
   "<MOVEMENTCOMPLETE-RESPONSE>"
   "MOVEMENTCOMPLETE-RESPONSE"
  ))

