// Generated by gencpp from file mover/MovementCompleteResponse.msg
// DO NOT EDIT!


#ifndef MOVER_MESSAGE_MOVEMENTCOMPLETERESPONSE_H
#define MOVER_MESSAGE_MOVEMENTCOMPLETERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mover
{
template <class ContainerAllocator>
struct MovementCompleteResponse_
{
  typedef MovementCompleteResponse_<ContainerAllocator> Type;

  MovementCompleteResponse_()
    : completed(false)  {
    }
  MovementCompleteResponse_(const ContainerAllocator& _alloc)
    : completed(false)  {
  (void)_alloc;
    }



   typedef uint8_t _completed_type;
  _completed_type completed;





  typedef boost::shared_ptr< ::mover::MovementCompleteResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mover::MovementCompleteResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MovementCompleteResponse_

typedef ::mover::MovementCompleteResponse_<std::allocator<void> > MovementCompleteResponse;

typedef boost::shared_ptr< ::mover::MovementCompleteResponse > MovementCompleteResponsePtr;
typedef boost::shared_ptr< ::mover::MovementCompleteResponse const> MovementCompleteResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mover::MovementCompleteResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mover::MovementCompleteResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mover::MovementCompleteResponse_<ContainerAllocator1> & lhs, const ::mover::MovementCompleteResponse_<ContainerAllocator2> & rhs)
{
  return lhs.completed == rhs.completed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mover::MovementCompleteResponse_<ContainerAllocator1> & lhs, const ::mover::MovementCompleteResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mover

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mover::MovementCompleteResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mover::MovementCompleteResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mover::MovementCompleteResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mover::MovementCompleteResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mover::MovementCompleteResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mover::MovementCompleteResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mover::MovementCompleteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e58faa17a4877a1efc0e251b503c53b";
  }

  static const char* value(const ::mover::MovementCompleteResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e58faa17a4877a1ULL;
  static const uint64_t static_value2 = 0xefc0e251b503c53bULL;
};

template<class ContainerAllocator>
struct DataType< ::mover::MovementCompleteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mover/MovementCompleteResponse";
  }

  static const char* value(const ::mover::MovementCompleteResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mover::MovementCompleteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool completed\n"
;
  }

  static const char* value(const ::mover::MovementCompleteResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mover::MovementCompleteResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.completed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MovementCompleteResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mover::MovementCompleteResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mover::MovementCompleteResponse_<ContainerAllocator>& v)
  {
    s << indent << "completed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.completed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVER_MESSAGE_MOVEMENTCOMPLETERESPONSE_H
